### ISSUE TITLE
Support an empty META field

### ISSUE THREAD

**Issue by panda-roux-dev** [makeworld-the-better-one/go-gemini#14]
The library wants response headers to have at least two fields, otherwise it will report this exception: https://github.com/makeworld-the-better-one/go-gemini/blob/156d3096e40b1a88eaa5c45cf91a387c3a901941/client.go#L422

However, clients should default to the gemtext MIME type if no META is provided.  This means that a response of `20CRLF` is valid.

See: https://github.com/makeworld-the-better-one/amfora/issues/176

You may test this on this page in one of my capsules, which returns `20` with no META field: gemini://library.inu.red/test

**Comment by makeworld-the-better-one** [comment]
> This means that a response of `20CRLF` is valid.

No, this response is not valid, which is why the library returns an error. See section 3.1 of the spec, which defines a response header as the format `<STATUS><SPACE><META><CR><LF> `. The `<META>` may be an empty string, but the preceding`<SPACE>` is not optional. A response header without a meta should look like `20 \r\n`.

Thanks for your interest in Amfora!
